server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /data/sites.csv {
        add_header Cache-Control "no-store" always;
        default_type text/csv;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
